version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-network

  server:
    build:
      context: ./server
    container_name: node-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./server/.env
    networks:
      - mern-network

  client:
    build:
      context: ./client
    container_name: react-client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data: