version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - server
    networks:
      - mern-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    container_name: node-server
    restart: always
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge