version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - client
      - server
    networks:
      - mern-network
    extra_hosts:
      - "firewall:192.168.100.90"
      - "waf:192.168.20.13"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: node-server
    restart: always
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb
    networks:
      - mern-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: react-client
    restart: always
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data:
  uploads_data:
